corrrector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('note/', admin.site.urls),
]

notes/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from  . import views

app_name = 'notes'

urlpatterns = [
    path('', views.ListNotes.as_view(), name="all"),
    path('nueva/', views.CreateNote.as_view(), name="create"),
    path('by/<str:username>/<int:pk>/', views.SingleNote.as_view(), name="single"),
    path('update/', views.EditNote.as_view(), name="update"),
    path('by/<str:username>/<int:pk>/update/', views.EditNote.as_view(), name="update"),
    re_path(r'^borrar/(?P<pk>\d+)/$', views.DeleteNote.as_view(), name="delete"),
]
# url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$", views.SingleNote.as_view(), name="single"),

notes/models.py
from django import template
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone
from django.utils.text import slugify
from django.urls import reverse
from django.conf import settings
import misaka

User = get_user_model()
register = template.Library()

class Note(models.Model):
    user = models.ForeignKey(User, related_name='notes', on_delete=models.CASCADE)
    title = models.CharField(max_length=255, unique=False)
    slug = models.SlugField(allow_unicode=True, unique=True)
    content = models.TextField(blank=False, default='')
    content_html = models.TextField(editable=False, blank=True, default='')
    created_at = models.DateTimeField(editable=False)
    updated_at = models.DateTimeField()

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.id:
            self.created_at = timezone.now()
        self.updated_at = timezone.now()
        self.slug = slugify(self.title)
        self.content_html = misaka.html(self.content)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse(
            "notes:single",
            kwargs={
                "username": self.user.username,
                "pk": self.pk,
            }
        )

    class Meta:
        ordering = ['-updated_at']
        unique_together = ['user', 'content']

class Error(models.Model):
    note = models.ForeignKey(Note, related_name='errors', on_delete=models.CASCADE)
    phrase = models.CharField(editable=False, max_length=512, unique=False)
    suggestion = models.CharField(editable=False, max_length=512, unique=False)
    explanation = models.TextField(editable=False, blank=True, default='')

    def __str__(self):
        return self.explanation[:30]

notes/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse, reverse_lazy
from django.http import Http404
from django.views import generic
from braces.views import SelectRelatedMixin
from django.contrib import messages
from . import models
from . import forms

User = get_user_model()

class CreateNote(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    fields = ('title', 'content')
    model = models.Note

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

class DeleteNote(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    model = models.Note
    select_related = ('user')
    success_url = reverse_lazy('notes:all')

    def get_queryset(self):
        return super().get_queryset().filter(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, "Nota eliminada")
        return super().delete(*args, **kwargs)

class SingleNote(generic.DetailView):
    model = models.Note

    def get_queryset(self):
        return super().get_queryset()

class EditNote(LoginRequiredMixin, generic.UpdateView):
    fields = ('title', 'content')
    model = models.Note
    template_name_suffix = '_update'

    def get_queryset(self):
        # TODO: get the note's content and call a new method to get errors
        return super().get_queryset()
    
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

class ListNotes(generic.ListView):
    model = models.Note
    template_name = 'authentication/home.html'
    
    def get_queryset(self):
        self.note_user = self.request.user
        if self.request.user.is_authenticated:
            return models.Note.objects.filter(user=self.note_user)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["note_user"] = self.note_user
        return context

notes/templates/notes/_error.html
<div class="card">
  <div class="card-body">
    <h5 class="card-title">{{ error.phrase }} -> {{ error.suggestion }}</h5>
    <p class="card-text">{{ error.explanation }}</p>
    <a href="#" class="btn btn-primary" style="background-color: #77cbb9; border-color: #77cbb9;">corregir</a>
  </div>
</div>

notes/templates/notes/_note.html
{% load humanize %}
<div class="card">
    <div class="card-body">
        <h5 class="card-title">{{ note.title }}</h5>
        <p class="card-text">{{ note.content|slice:":180" }}</p>
        <a href="{% url 'notes:update' username=note.user.username pk=note.pk %}" class="btn btn-primary" style="background-color: #77cbb9; border-color: #77cbb9;">Ver nota</a>
    </div>
    <div class="card-footer">
        <small class="text-muted">Ultima actualización: {{ note.updated_at|naturaltime }}</small>
    </div>
</div>

notes/templates/notes/note_base.html
{% extends 'authentication/base.html' %}

{% block content %}

<div>
    <div>
        {% block prenote %}{% endblock %}
        </br>
        {% block note_content %}{% endblock %}
        </br>
        {% block postnote %}{% endblock %}
    </div>
</div>

{% endblock %}

notes/templates/notes/note_confirm_delete.html
{% extends 'notes/note_base.html' %}

{% block note_content %}
<div class="modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Borrar nota</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Estás a punto de eliminar esta nota.</p>
      </div>
      <div class="modal-footer">
        <a type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</a>
        <a type="button" href="{% url 'notes:single' username=user.username pk=object.pk %}" class="btn btn-primary" style="background-color: #77cbb9; border-color: #77cbb9;">Continuar</a>
      </div>
    </div>
  </div>
</div>
{% endblock note_content %}

notes/templates/notes/note_detail.html
{% extends 'notes/note_base.html' %}
{% load humanize %}

{% block prenote %}
<h3>
    {{note.title}}
    <small class="text-muted">Ultima actualización: {{ note.updated_at|naturaltime }}</small>
</h3>
{% endblock  %}

{% block note_content %}
{% include "notes/_note.html" %}
{% endblock %}

notes/templates/notes/note_form.html
{% extends 'notes/note_base.html' %}
{% load bootstrap4 %}

{% block prenote %}
<h2>Nueva nota</h2>
{% endblock  %}

{% block note_content %}
<div class="container">
  <div class="row">
    <div class="col-8">
        <form method="POST" action="{% url 'notes:create' %}">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button type="submit" class="btn btn-dark" style="background-color: #1c1c1c; border-color: #1c1c1c;">Guardar</button>
        </form>
    </div>
    <div class="col-4">
        <!--TODO list of errors-->
    </div>
  </div>
</div>
{% endblock  %}

notes/templates/notes/note_update.html
{% extends 'notes/note_base.html' %}
{% load humanize %}
{% load bootstrap4 %}

{% block prenote %}
<h3>
    {{note.title}}
    <small class="text-muted">Ultima actualización: {{ note.updated_at|naturaltime }}</small>
</h3>
{% endblock  %}

{% block note_content %}
<div class="container">
  <div class="row">
    <div class="col-8">
        <form method="POST" action="{% url 'notes:update' %}">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button type="submit" class="btn btn-dark" style="background-color: #1c1c1c; border-color: #1c1c1c;">Actualizar</button>
        </form>
    </div>
    <div class="col-4">
        <!--TODO list of errors-->
    </div>
  </div>
</div>
{% endblock %}